### ISSUE TITLE
CUDA out-of-memory error

### ISSUE THREAD

**Issue by joneswong** [snap-stanford/GraphGym#10]
I tried to execute run_batch.sh. It seems that there is no mechanism to block the emerging of trials, as there are more and more processes running in my GPUs. And I observed the out-of-memory error of CUDA.

**Comment by JiaxuanYou** [comment]
You can control the number of concurrent job:
`bash parallel.sh configs/${CONFIG}_grid_${GRID} $REPEAT $MAX_JOBS $SLEEP`
Here the `$MAX_JOBS` does that, you can set a lower number.

**Comment by joneswong** [comment]
hi jiaxuan, I noticed that the issue is caused by that my shell regard the `wait -n` command as an invalid one (see parallel.sh). I can resolve it by the following script customized from https://stackoverflow.com/questions/6593531/running-a-limited-number-of-child-processes-in-parallel-in-bash

```
CONFIG_DIR=$1
REPEAT=$2
MAX_JOBS=${3:-2}
SLEEP=${4:-1}

todo_array=($(find $CONFIG_DIR -type f)) # places output into an array

index=0

function add_next_job {
    # if still jobs to do then add one
    if [[ $index -lt ${#todo_array[*]} ]]
    # apparently stackoverflow doesn't like bash syntax
    # the hash in the if is not a comment - rather it's bash awkward way of getting its length
    then
        echo adding job ${todo_array[$index]}
        do_job ${todo_array[$index]} &
        # replace the line above with the command you want
        index=$(($index+1))
    fi
}

function do_job {
    echo "starting job $1"
    python main.py --cfg $1 --repeat $REPEAT --mark_done
    sleep $SLEEP
}

set -o monitor
# means: run background processes in a separate processes...
trap add_next_job CHLD
# execute add_next_job when we receive a child complete signal

# add initial set of jobs
while [[ $index -lt $MAX_JOBS ]]
do
    add_next_job
done

# wait for all jobs to complete
wait
echo "done"
```

If it is needed, I am glad to make a pr.
