### ISSUE TITLE
batch training ogb-molhiv

### ISSUE THREAD

**Issue by jkamalu** [snap-stanford/GraphGym#12]
I am running a graph classification model on ogb-molhiv.

My model's forward function is being passed a batch with the following fields/shapes.

> Batch(G=[128], batch=[3512], edge_feature=[7498, 3], edge_index=[2, 7498], edge_label_index=[2, 7498], graph_label=[128, 1], node_feature=[3512, 128], node_label_index=[3512], task=[128])

This dataset has ~40,000 graphs with ~25 nodes per graph. The batch info is present in the batch.batch tensor, but how do I do batch training here, processing each batch independently i.e. predict y0 given nodeset0 and edgeset0?

I forked the repo and include a comparison here: https://github.com/snap-stanford/GraphGym/compare/master...jkamalu:gmt

**Comment by JiaxuanYou** [comment]
Thanks for the question.
The idea of batching is to combine 128 graphs into a large graph with 128 disconnected components.
Here you are already doing batch training, where "graph_label" is predicted for all the 128 graphs. "batch" is used to indicate which node belongs to which graph. Hope this answers your question.
