### ISSUE TITLE
about configs_gen.py

### ISSUE THREAD

**Issue by HodaMemar** [snap-stanford/GraphGym#17]
Hello
Thank you for Machine Learning on Graph courses. I identify GraphGym through it.

I have a question about installing GraphGym.
I try on colab
I follow the instruction, but I get this error:

![image](https://user-images.githubusercontent.com/66674325/118386887-e6fd2500-b62f-11eb-9461-833243e82675.png)

What change should I make?

Thank you.

**Comment by JiaxuanYou** [comment]
Hi! I'm not sure the context of the piece of code you presented. I think you didn't set your value for $REPEAT.
You can refer to a full example here: https://github.com/snap-stanford/GraphGym/blob/master/run/run_batch.sh
You should be able to run that bash script without a problem.
