### ISSUE TITLE
Lack of support for Generative Model

### ISSUE THREAD

**Issue by nashid** [snap-stanford/GraphGym#18]
I want to apply GNN to new applications i.e. Scenario 2 (**Scenario 2: You want to apply GNN to your exciting applications.**)

I see all the models are for predictive tasks. 

I am wondering whether you are planning to include generative models in the future?

For example, whether there are any plans to include any of the following models:

- GraphRNN: https://github.com/JiaxuanYou/graph-generation

Also, it lacks examples of any **Graph2Seq** based models. It would be awesome to include consider any of the following **Graph2Seq** based **generative models**.

- Graph-to-Sequence Learning using Gated Graph Neural Networks, ACL’18
https://github.com/beckdaniel/acl2018_graph2seq
Using MXNet

- Densely Connected Graph Convolutional Networks for Graph-to-Sequence Learning, ACL’19
https://github.com/Cartus/DCGCN
Using MXNet 1.3.0

- Gated Graph Sequence Neural Networks, Y. Li, D. Tarlow, M. Brockschmidt, and R. Zemel.

- Heterogeneous Graph Transformer for Graph-to-Sequence Learning, ACL’18 
https://github.com/QAQ-v/HetGT 

Including any other generative model would be a great starting point as well.

I am really interested to know your thoughts in this regard.

**Comment by JiaxuanYou** [comment]
Thanks for your interest. For now GraphGym will focus on predictive tasks, since generative tasks have very different objectives, models and evaluation protocols, so it may require very different pipelines. 
However, if you like to try it out, I'm happy to provide some suggestions.
