### ISSUE TITLE
running simple example on CPU

### ISSUE THREAD

**Issue by kyleiwaniec** [snap-stanford/GraphGym#19]
Hi @JiaxuanYou,

Thank you for making this code base available!

I do not have an NVIDIA GPU. So I tried to run the example on CPU. However, I ran into errors because the logger was calling the `get_current_gpu_usage()` function in `device.py` .

To fix this, I wrapped this function in the same conditional as the `auto_select_device()` function like so:

```
def get_current_gpu_usage():
    if cfg.device != 'cpu' and torch.cuda.is_available():
        result = subprocess.check_output(
            [
                'nvidia-smi', '--query-compute-apps=pid,used_memory',
                '--format=csv,nounits,noheader'
            ], encoding='utf-8')
        current_pid = os.getpid()
        used_memory = 0
        for line in result.strip().split('\n'):
            line = line.split(', ')
            if current_pid == int(line[0]):
                used_memory += int(line[1])
        return used_memory
    else:
        return 0
```

Just wanted to let you know. You may have a better way to do it :)

Kyle

**Comment by nashid** [comment]
@JiaxuanYou it would be awesome to have GraphGym running with CPU! While developing/proto-typing its a common use-case to use CPU-only environment.

**Comment by JiaxuanYou** [comment]
Thanks for the feedback! I'll fix support for CPU soon.

**Comment by JiaxuanYou** [comment]
Thanks @kyleiwaniec for posting the fix!
I have verified that the support for CPU was broken by the pull request #15 , where we assumed that GPU is available. Other than that, GraphGym should work with CPU without a problem. 
The only thing you need to do is to set in your `.yaml` file: `device: cpu`, and you should be all set.

I created an example in `run/run_single_cpu.sh`, and you can try it out.

If anything went wrong, please feel free to reopen the issue.

@nashid @zhiyun-deng
