### ISSUE TITLE
Root node not considered for message-passing in GeneralConv

### ISSUE THREAD

**Issue by danielegrattarola** [snap-stanford/GraphGym#2]
Hi, 

this is not technically an issue but more of a general question, I apologize if this is not the best place to ask. 

Looking at the `GeneralConv` layer, it seems that the representation for a given node is, by default, only computed from the neighbours and not the node itself: 

https://github.com/snap-stanford/GraphGym/blob/77f1e7acb4d08b6647b2cf1d147d86b736ac25e2/graphgym/contrib/layer/generalconv.py#L85-L86

This is only true if `normalize=False` in the layer, because the `norm` staticmethod has a call to `add_remaning_self_loop` that effectively adds nodes into their own neighbourhood:

https://github.com/snap-stanford/GraphGym/blob/77f1e7acb4d08b6647b2cf1d147d86b736ac25e2/graphgym/contrib/layer/generalconv.py#L51-L52

If `normalize=False` the call to `norm` is skipped and so a node is not neighbour of itself.
I was wondering if this is intentional, and if so what is the rationale behind this design choice.

I am re-implementing this layer for another GNN library and I need to make a choice about whether to process nodes as part of their neighbourhood.
I know that 1) in the paper and 2) in the code there is no ambiguity about this fact, but it sounds strange to me so I wanted to double-check with you :D

Thanks

**Comment by JiaxuanYou** [comment]
Thanks Daniel for pointing this out!
Yes, you are right that the current implementation does not explicitly consider the message from the node itself.
To have that implementation, there are 2 possibilities:
- User include selfloop edges (e.g., [1,1]) in the edge_index. Then the current implementation can work.
- User does not include selfloop edges. This way, you may want to explicitly consider messages from the node itself in the message passing layer.
An alternative implementation (which proves to work well in GraphGym) is the use of skip connection. You can understand skip connection as a way of adding self messages to the node itself.

What I'm trying to explain is that there are many alternative implementations for adding self messages. If you like, you may register your favorite implementation to your GraphGym copy in `graphgym/contrib/layer`; it should be fairly simple. If you'd like to create a pull request that will be great. The way I use GraphGym in my current research is to register many customized modules to satisfy special needs.

Hope these make sense!

**Comment by danielegrattarola** [comment]
Thanks for the reply, I agree that skip connections are equivalent to using the root node in the MP. 

Cheers
