### ISSUE TITLE
Support for Multi Label Classification and Neighbour Sampling for Message Passing

### ISSUE THREAD

**Issue by milindkesar** [snap-stanford/GraphGym#22]
Hi,
In the current version there is no option of sampling neighbours while message passing and support for multi label node classification for datasets such as PPI right? Could you let me know if I am missing something?

Thank You.

**Comment by JiaxuanYou** [comment]
Yes, currently only full batch training is supported. But I do plan to support scalable GNN training algorithms in the future, potentially around October this year.
