### ISSUE TITLE
What is the difference between GraphGym and DeepSnap?  

### ISSUE THREAD

**Issue by cloudyuyuyu** [snap-stanford/GraphGym#27]
I am a beginer of gnn

how do i choose lib to study?

**Comment by xnhp** [comment]
GraphGym is a framework for evaluating different GNN architectures.

GraphGym actually uses DeepSNAP internally to represent graphs.

I think If you only want to simply train and compare different GNN
architectures you should look at GraphGym.

To what extent you can use DeepSNAP alone depends on your use-case I would
say.

**Comment by cloudyuyuyu** [comment]
thanks for your reply
