### ISSUE TITLE
error in configs/idgnn/graph_enzyme.yaml

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [snap-stanford/GraphGym#29]
Thank you for the nice library. I noticed that the under ```configs/IDGNN/graph_enzyme.yaml```, the name of the dataset is ba500. I guess this is a bug? Would you like to update the yaml file? Thank you!

**Comment by JiaxuanYou** [comment]
Thanks for spotting this. No, it is not a bug.
In ID-GNN, we have two types of datasets for link prediction (`ba`, `ws`] and for graph classification [`ba500`, `ws500`]. For link prediction, we use fewer than 500 graphs.
