### ISSUE TITLE
question about IDGNN

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [snap-stanford/GraphGym#30]
Hello,

I am interested in reproducing the IDGNN's results on graph classification. I looked at the code and had a few quick questions
1) are all configurations listed in https://github.com/snap-stanford/GraphGym/blob/master/run/grids/IDGNN/graph_enzyme.txt? i.e., the major arguments I need to change is ```dataset.augment_feature```?  I am mainly interested in reproducing results at Table 6. 

2) there are ID-GNN and ID-GNN-Fast. Are both implemented in this repository? 

3) how is the heterogeneous message passing is implemented?

Thank you very much!!

**Comment by JiaxuanYou** [comment]
Thanks for the questions.

1. For all the IDGNN experiments, please check https://github.com/snap-stanford/GraphGym/blob/master/run/grids/IDGNN/graph.txt
`graph_enzyme` is the experiments for `enzyme` dataset only (where a smaller model is used)

2. Yes, ID-GNN-Fast is implemented as well. `dataset.augment_feature = 'node_identity'` is for ID-GNN-Fast.

3. Please checkout this file https://github.com/snap-stanford/GraphGym/blob/master/graphgym/contrib/layer/idconv.py
