### ISSUE TITLE
Custom PyG dataset usage

### ISSUE THREAD

**Issue by Laolga** [snap-stanford/GraphGym#31]
Hi! I'm a little confused if it's actually possible to use my own dataset in a PyG format or not. 
load_pyg function kind of suggests that the name of a dataset can only be one of the fixed ones (CiteSeer, PPI, Cora, etc) while the readme states that a PyG upload should be possible: "GraphGym currently accepts a list of NetworkX graphs or PyG datasets.". 
If PyG format for the custom data is not possible then I guess it must be networkx. Is there any example how those graphs should look like? In particular, I'm interested in graph classification, if that matters.

Olga

**Comment by xnhp** [comment]
Hi Olga,

it's possible. What the simplest approach is depends on the format your
data is in.

The most general way is to implement a custom "loader" function (an example
is in the "contrib" subdirectory). A loader is a function that returns a
list of DeepSNAP graphs, if I remember correctly. Then, in your
experiment's config file, you specify to use that loader.

Best Regards,
Ben

**Comment by Laolga** [comment]
Thanks! Understood now.
