### ISSUE TITLE
Error producing results

### ISSUE THREAD

**Issue by Laolga** [snap-stanford/GraphGym#32]
The execution goes pretty smoothly and then at the very end outputs this
```
train: {'epoch': 399, 'eta': 0.0, 'loss': 0.6025, 'lr': 0.0, 'params': 265218, 'time_iter': 0.0837, 'accuracy': 0.688, 'precision': 0.5556, 'recall': 0.0324, 'f1': 0.0612, 'auc': 0.6239}
val: {'epoch': 399, 'loss': 0.6162, 'lr': 0, 'params': 265218, 'time_iter': 0.0465, 'accuracy': 0.6667, 'precision': 0.6, 'recall': 0.0361, 'f1': 0.0682, 'auc': 0.6527}
test: {'epoch': 399, 'loss': 0.6214, 'lr': 0, 'params': 265218, 'time_iter': 0.0448, 'accuracy': 0.6545, 'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'auc': 0.6245}
Check point saved: results/example/1/ckpt/399.ckpt
Task done, results saved in results/example/1
359
{'epoch': 359, 'loss': 0.6233, 'lr': 0, 'params': 265218, 'time_iter': 0.0455, 'accuracy': 0.6585, 'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'auc': 0.6213}
{'epoch': 359, 'eta': 210.5677, 'loss': 0.6055, 'lr': 0.0003, 'params': 265218, 'time_iter': 0.0848, 'accuracy': 0.689, 'precision': 0.6667, 'recall': 0.0194, 'f1': 0.0377, 'auc': 0.6138}
{'epoch': 359, 'loss': 0.6175, 'lr': 0, 'params': 265218, 'time_iter': 0.0472, 'accuracy': 0.6707, 'precision': 0.75, 'recall': 0.0361, 'f1': 0.069, 'auc': 0.655}
239
{'epoch': 239, 'eta': 2.2639, 'loss': 0.0281, 'lr': 0.0035, 'params': 632328, 'time_iter': 0.0143, 'accuracy': 0.9991}
{'epoch': 239, 'loss': 0.4795, 'lr': 0, 'params': 632328, 'time_iter': 0.0079, 'accuracy': 0.8819}
359
{'epoch': 359, 'eta': 0.573, 'loss': 0.0139, 'lr': 0.0003, 'params': 632328, 'time_iter': 0.0154, 'accuracy': 1.0}
{'epoch': 359, 'loss': 0.4917, 'lr': 0, 'params': 632328, 'time_iter': 0.0073, 'accuracy': 0.8875}
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    agg_runs(get_parent_dir(out_dir_parent, args.cfg_file), cfg.metric_best)
  File "/nfs/data/patients_networks/olga_scripts/GraphGym/graphgym/utils/agg_runs.py", line 110, in agg_runs
    results[key][i] = agg_dict_list(results[key][i])
  File "/nfs/data/patients_networks/olga_scripts/GraphGym/graphgym/utils/agg_runs.py", line 47, in agg_dict_list
    value = np.array([dict[key] for dict in dict_list])
  File "/nfs/data/patients_networks/olga_scripts/GraphGym/graphgym/utils/agg_runs.py", line 47, in <listcomp>
    value = np.array([dict[key] for dict in dict_list])
KeyError: 'precision'

```
Results folder is produced, but there are only accuracy metrics and no "test" folder. I suspect that maybe it's related to the fact that the precision is equal to 0 on the test set.

**Comment by xnhp** [comment]
Commenting off the top of my head here. This may be because precision is
not even evaluated, check your config, I think there's an option to specify
evaluation metrics (check the python files, i.e. what is imported as "cfg"
throughout GG code for available config keys and their default value).
agg_runs aggregates results from different repeats iirc. The stacktrace
says that particular metric is not present in the dict. I think that dict
is obtained by reading the individual run results from disk.

**Comment by Laolga** [comment]
So I specified cfg.metric_best = 'f1' (before it was the default)  and also just in case made my classification balanced, ran the grid search and faced the same issue. For most of the runs agg folder is not even created because of the same error => can not evaluate the grid search results. Not sure which script exactly creates the agg folder for each run, but the bug must be there.

**Comment by JiaxuanYou** [comment]
Thanks @Laolga for the question, and @xnhp for helping explain the mechanism!
@Laolga, to clarify, the only thing you have changed is to change the `cfg.metric_best = 'f1'`?
Which grid of experiments do you run?

**Comment by xnhp** [comment]
From what I remember of another thread I think they're trying to set up their own experiment...?

**Comment by Laolga** [comment]
> Thanks @Laolga for the question, and @xnhp for helping explain the mechanism! @Laolga, to clarify, the only thing you have changed is to change the `cfg.metric_best = 'f1'`? Which grid of experiments do you run?

I run the experiments on my custom dataset with approx. 3000 graphs, balanced binary classification. In my previous experiments with pytorch geometric and very basic architecture, I'm reaching ~0.7 accuracy on it, so the dataset should not be too hard.
For the grid I'm using the standard example with 96 configurations. In the config file I only changed lines relevant for my classification (directory, task, type of the task ). I've changed the metric to f1 hoping that it will prevent the error above, but it doesn't.
The error I'm getting with the grid search is also related to the precision and prevents creation of the `agg` folder in some cases (9/10 approximately).

`/nfs/home/users/olgala/.conda/envs/cuda_torch/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
`

**Comment by xnhp** [comment]
The warning you pasted is printed during training, right?

The message means that there are no positive predictions, i.e. your model
is not performing well at all.

If it is really the case that if there are no positive predictions, output
is not generated correctly then that's indeed a bug and you either have to
fix it yourself (doable) or hope for someone to do it.

**Comment by JiaxuanYou** [comment]
Close this for now unless @Laolga has further questions. Thanks for the lively discussion here!
