### ISSUE TITLE
About the MetaLink code

### ISSUE THREAD

**Issue by yaoman3** [snap-stanford/GraphGym#44]
Hi, in the paper "RELATIONAL MULTI-TASK LEARNING: MODELING RELATIONS BETWEEN DATA AND TASKS", the authors said the code has been released in this repository, but we could not find it. Could we know which part of the code is about MetaLink? Thanks.

**Comment by JiaxuanYou** [comment]
Yes. It's in this branch: https://github.com/snap-stanford/GraphGym/tree/meta_link
