### ISSUE TITLE
PRED vectors are wrongly flattened when there are trailing dimensions in TRUE vectors.

### ISSUE THREAD

**Issue by Guangxuan-Xiao** [snap-stanford/GraphGym#6]
https://github.com/snap-stanford/GraphGym/blob/fa133e55a07ed67ba769f8165c99437ea1410e50/graphgym/loss.py#L22-L25

When the shape of the label vector `true` is `[node_num, 1]` instead of `[node_num]`, lines 22-23 will misinterpret the task as a multi-task binary classification task rather than a multi-class classification task. So the `pred` vector will be wrongly flattened. The correct code should be
```python
    pred = pred.squeeze(-1) if pred.ndim > 1 else pred
    true = true.squeeze(-1) if true.ndim > 1 else true
    if true.ndim > 1 and cfg.model.loss_fun == 'cross_entropy':
        pred, true = torch.flatten(pred), torch.flatten(true)
```
, which moves lines 24-25 to the front of lines 22-23.

**Comment by JiaxuanYou** [comment]
Thanks! It makes sense and I've updated the code
