### ISSUE TITLE
Message-passing layers should be built when layers_mp > 0 instead of 1

### ISSUE THREAD

**Issue by Guangxuan-Xiao** [snap-stanford/GraphGym#7]
https://github.com/snap-stanford/GraphGym/blob/cf65c93d984bde01075856044af44064760d2a68/graphgym/models/gnn.py#L157

When `cfg.gnn.layers_mp == 1`， GNN should have one message-passing layer, while the code here will not build `self.mp`.

The correct code may be:
```python
if cfg.gnn.layers_mp > 0: 
```

**Comment by JiaxuanYou** [comment]
Thanks, it makes sense. In practice we only used layers_mp >= 2.
