### ISSUE TITLE
Issue with create_dataset() in loader.py

### ISSUE THREAD

**Issue by ShineCxy10** [snap-stanford/GraphGym#8]
Hi! Thank you for the great tool for working with GNN! However, it seems to me that there is probably an issue with the  create_dataset() function in loader.py. Specifically, when calling GraphDataset(), it assigns "cfg.dataset.resample_disjoint" to "resample_disjoint". However, the GraphDataset does not have an attribute "resample_disjoint". I am wondering whether that should be "edge_train_mode" instead.

**Comment by ShineCxy10** [comment]
Just to be clear, it seems that "resample_disjoint" is a member function of GraphDataset() instead of a member attribute, and thus triggers "TypeError: __init__() got an unexpected keyword argument 'resample_disjoint'" when I tried to create the graph dataset.

**Comment by JiaxuanYou** [comment]
Hi, thanks for spotting this issue. I think you are probably using an older version of DeepSNAP.
Could you try to install the latest DeepSNAP from github? (https://github.com/snap-stanford/deepsnap)

You can see that the latest DeepSNAP has "resample_disjoint" attribute 
(https://github.com/snap-stanford/deepsnap/blob/c028acfb839d2add4fcc2254f7fb591c650188e7/deepsnap/dataset.py#L188)

**Comment by ShineCxy10** [comment]
Thank you! It's weird that when I did "pip install deepsnap==0.1.2", the GraphDataset() in the package source file still seemed to be of the old version. However, it worked after I manually cloned the DeepSNAP git repo and put it into the python site-packages.
