### ISSUE TITLE
Invalid argument for DeepSNAP GraphDataset

### ISSUE THREAD

**Issue by joneswong** [snap-stanford/GraphGym#9]
I encountered the issue when I tried the run_single.sh. After checking the doc of DeepSNAP, I think this line should be commented out

https://github.com/snap-stanford/GraphGym/blob/b36bdaf7673246ea92e6303840eec885830579b2/graphgym/loader.py#L211

**Comment by JiaxuanYou** [comment]
Thanks for spotting this. 
You can install the latest DeepSNAP here: https://github.com/snap-stanford/deepsnap
The pip version of DeepSNAP is not the latest one

**Comment by JiaxuanYou** [comment]
I have updated the documentation and you can follow the new Readme to install DeepSNAP. Hope it helps.
